require('dotenv').config();
const mongoose = require('mongoose');

const MONGO_URI = process.env.MONGODB_URI;

const propertySchema = new mongoose.Schema({
  name: String,
  type: String,
  description: String,
  location: {
    street: String,
    city: String,
    state: String,
    zipcode: String,
  },
  beds: Number,
  baths: Number,
  square_feet: Number,
  amenities: [String],
  rates: {
    nightly: Number,
    weekly: Number,
    monthly: Number,
    sale: Boolean,
    price: String,
  },
  seller_info: {
    name: String,
    email: String,
    phone: String,
  },
  images: [String],
  is_featured: Boolean,
  owner: String,
  covered_area: Number,
  garage: Number,
  services: [String],
  titles_status: String,
  interior: {
    aberturas: String,
    pisos: String,
    calefaccion: String,
  },
  exterior: {
    techos: String,
  },
  price: String,
  operation: { type: String, enum: ['compra', 'venta', 'alquiler'] },
  status: { type: String, enum: ['active', 'PRECIO MEJORADO', 'ULTIMA UNIDAD', 'UNICO EN SU TIPO', 'NUEVA'], default: 'active' },
  property_type: { type: String, enum: ['residential', 'multi_family', 'land', 'commercial', 'rental', 'industrial'] },
}, { timestamps: true });

const Property = mongoose.model('Property', propertySchema);

const properties = [
  {
    name: 'Importante Casona de estilo en Barrio Pellegrini',
    type: 'Casa',
    description: 'Se trata de "Villa Roma", una icónica e importante casona de estilo en Alta Gracia, ubicada en inmejorable zona estratégica, dentro de B° Pellegrini a pocos metros del Sierras Hotel, a 4 cuadras del Alta Gracia Golf Club, sobre un terreno de casi 2000 metros en una característica esquina de la ciudad. Con 465 m2 cubiertos ofrece 5 dormitorios de buen tamaño con pisos de madera y la mayoría con acceso directo al exterior a través de balcones y galerías en otros casos, 2 amplios baños de época, un living con acceso independiente al final del pasillo en el ala Norte, que conecta con una galería cerrada vidriada o patio de invierno, un comedor de importante tamaño conectado al ingreso principal de la propiedad, adyacente a un comedor diario y posterior cocina con acceso lateral independiente. También cuenta con garaje mas dependencias (dormitorio adjunto, baño y cocina), 2 depósitos en la parte posterior y altillo o entrepiso que ocupa el total de la superficie cubierta. El parque presenta desniveles totalmente aprovechables y amplias posibilidades de desarrollo tanto para vivienda particular como para un desarrollo de tipo comercial gracias a sus 155 metros sobre calles Achával Rodríguez y Avellaneda. Posee hermosos arboles, palmeras y plantas. El inmueble requiere de puesta en valor, sin embargo la mayor parte del mismo esta en buenas condiciones y habitable, se encuentra inventariado como patrimonio histórico de la ciudad lo que otorga una distinción especial. Detalles arquitectónicos, escaleras, arcadas, postigones, pisos de materiales específicos y diseño se conjugan brindar gran belleza y la potencialidad de lograr una de las propiedades más distinguidas de la ciudad con la adecuada inversión. Sin dudas una verdadera joya en bruto para quien desee realizar un proyecto de este tipo.',
    location: { street: 'Achával Rodríguez y Avellaneda, Barrio Pellegrini', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 5, baths: 2, square_feet: 465,
    amenities: ['Patio', 'Jardín', 'Cochera', 'Parrilla', 'Dependencias', 'Altillo'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2021/09/CASONA-ACHAVAL-11.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2021/09/CASONA-ACHAVAL-13.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2021/09/CASONA-ACHAVAL-29.jpg'],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: 465, garage: 1,
    services: ['Luz', 'Agua de Red', 'Gas Natural', 'Cloacas'],
    titles_status: 'Perfectos',
    interior: { aberturas: 'Madera', pisos: 'Pinotea y baldosas originales', calefaccion: 'Calefactor en living y salamandra en pasillo' },
    exterior: { techos: 'Madera y Teja' },
    price: 'USD 320,000',
  },
  {
    name: 'Alta Gracia, Córdoba, Lote de 1.216 m2 en Alta Gracia Country Golf',
    type: 'Terreno',
    description: 'Lote de 1.216 m2 en Alta Gracia Country Golf. Servicios: Agua, Luz, Gas, Cloacas y Adoquinado (fin de 2026). Títulos perfectos.',
    location: { street: '', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 1216,
    amenities: ['Seguridad 24hs', 'Golf', 'Agua', 'Luz', 'Gas', 'Cloacas', 'Adoquinado'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2026/01/L13MZ473AGCG-2.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2026/01/L13MZ473AGCG-15.jpg'],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Agua', 'Luz', 'Gas', 'Cloacas', 'Adoquinado (fin de 2026)'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 70,000',
  },
  {
    name: 'Alta Gracia, Córdoba, Departamento de 2 Dormitorios en zona de El Golf',
    type: 'Departamento',
    description: 'Departamento de 2 dormitorios en zona de El Golf, Alta Gracia, Córdoba. Sup. Cub. interna 98m2, Balcones 19m2, Terraza 38m2. 3 baños, Lavadero independiente, Cochera. Calefacción: AA Central y Losa Radiante. Amenities: Piscina 80m2, SUM con asador y baños. Servicios: Luz, Agua de Red, Gas Natural, Cloacas.',
    location: { street: '', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 2, baths: 3, square_feet: 98,
    amenities: ['Piscina', 'SUM', 'Asador', 'Lavadero', 'Cochera', 'Balcones', 'Terraza'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/10/PALMETTO-2DORM-5.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/10/PALMETTO-2DORM-2.jpg'],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: 98, garage: 1,
    services: ['Luz', 'Agua de Red', 'Gas Natural', 'Cloacas'],
    titles_status: null,
    interior: { aberturas: null, pisos: null, calefaccion: 'AA Central y Losa Radiante' },
    exterior: {},
    price: 'USD 200,000 (Amoblado)',
  },
  {
    name: 'Alta Gracia, Córdoba, Duplex a Estrenar de 3 Dormatorios en B° Pellegrini',
    type: 'Casa',
    description: 'Duplex a estrenar de 3 dormatorios en B° Pellegrini, Alta Gracia, Córdoba.',
    location: { street: 'Bv. Pellegrini, Alta Gracia', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 3, baths: null, square_feet: null,
    amenities: ['Patio', 'Cochera', 'Parrilla'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: [],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz', 'Agua', 'Gas', 'Cloacas'],
    titles_status: null,
    interior: {},
    exterior: {},
    price: null,
  },
  {
    name: 'Alta Gracia, Córdoba, Impecable Posada de 6 habitaciones en funcionamiento',
    type: 'Gran Inversión',
    description: 'Se venta hermosa Posada en la ciudad de Alta Gracia, a 30 minutos de Córdoba Capital por autopista, a 20 minutos de Carlos Paz, a 35 minutos de lago Los Molinos y a 40 minutos de Villa General Belgrano; es una zona estratégica en la provincia de Córdoba para el turismo. El inmueble se encuentra ubicado a pocos metros de Barrio Pellegrini, por lo que ofrece excelente accesibilidad y entorno. Es una excelente oportunidad ya que se vende: Totalmente amoblada, en perfectas condiciones de mantenimiento y limpieza. Con base de clientes fija que se ha logrado gracias a años de excelente servicio y atención de los propietarios. Con personal de confianza, totalmente capacitado y entrenado para realizar las labores necesarias para un completo y acabado mantenimiento del inmueble y del negocio. En magnificas condiciones de mantenimiento y estructurales. HABITACIONES: Son 6 suites de 40 m2 insonorizadas con baño privado y zonificado, divididas en 3 categorías (Todas pueden ser doubles o triples): 2 JUNIOR: ducha con mampara de blindex. 2 SUPERIOR: bañera con Hidromasaje y mampara de blindex. 2 EJECUTIVA: bañera con Hidromasaje y mampara de blindex. Terraza privada con mesa y sillones. Cada habitación cuenta con: sommiers de 0,90 x 1,90, telefono interno, televisor LCD, frigobar, wet bar con hervidor eléctrico, caja de seguridad, mesa con sillas, aire acondicionado y calefacción, secador de pelo, espejo para maquillaje y calienta toallas. INSTALACIONES: 380m2 de espacio verde parquizado con mesas, sillones con sombrillas, reposeras de aluminio y bancos fijos de madera y mampostería. Piscina de 30m2 (7,5 m x 4 m) con equipo de filtrado y solárium. Terraza con quincho con asador y horno chileno. Club house con capacidad para 30/40 personas con mesas y sillas, juego de sillon doble, dos sillones individuales y mesa de living. Cocina con heladera con freezer, lavavajillas grande, cocina y carlitera. Predio totalmente cerrado monitoreado con 4 cámaras de seguridad. 6 cocheras cubiertas para automóviles o camionetas chicas. Portón de cochera operado desde la recepción y/o con control remoto. 2 cisternas de reserva de agua de 800 lts. Cada una con motor elevador automático. 2 termotanques a gas de alta recuperación de 110 lts. X minuto. WI-FI.',
    location: { street: '', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 6, baths: 9, square_feet: 576,
    amenities: ['WiFi', 'Aire Acondicionado', 'Piscina', 'Quincho', 'Seguridad 24hs', 'Estacionamiento', 'SUM'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2023/01/RAICESCAROLI-2.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2023/01/RAICESCAROLI-5.jpg'],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: 576, garage: 6,
    services: ['Luz', 'Agua de Red', 'Gas Natural', 'Cloacas', 'Internet', 'Telefono'],
    titles_status: null,
    interior: { aberturas: 'Aluminio', pisos: 'Cerámicos', calefaccion: 'AA' },
    exterior: { techos: 'Tejas' },
    price: 'USD 650,000',
  },
  {
    name: 'Córdoba, Los Aromos, Casa de 3 dormitorios a 250 mts del Río, 100% Refaccionada',
    type: 'Casa',
    description: 'Se venta hermosa propiedad construida sobre 2 lotes que suman 1600 m2 de superficie (matriculas individuales) con acceso directo sobre asfalto totalmente parquizados y muy cuidados. Está ubicada sobre la ruta que conecta La Bolsa con Alta Gracia. A pocos minutos de Alta Gracia y escasos metros de La Bolsa y el Río Anisacate (250 mts). La propiedad goza de una ubicación estratégica para acceder a las ciudades de Córdoba, Villa General Belgrano y Carlos Paz. Con 235 m2 cubiertos, el inmueble consta de 3 dormitorios de buen tamaño, 2 baños impecables y totalmente renovados, un ingreso amplio, living, cocina comedor amplio, moderno y muy luminoso con zona de lavadero cómoda y correctamente escondida. Todos estos ambientes han sido decorados y aggiornados con excelente gusto y calidad. Se ha aprovecha la distribución del inmueble para generar zonas independientes y funcionales, conjugando de manera correcta un estilo moderno a la construcción de época. Cuenta con un quincho abierto de buen tamaño, construido en la parte posterior del terreno donde se ha dejado el espacio perfecto para construir una pileta al mismo nivel del Quincho. Desde el portón de ingreso vehicular se accede a una cochera cubierta y un acceso independiente a la propiedad (zona de cocina/comedor). Así también, posee un acceso lateral gerarquizado con un porche revestido con un bello porcelanato. Se venta totalmente equipada y amoblada, dato que no es menor ya que así como se ha invertido sin escatimar en calidad y precio en la restauración y mantenimiento del inmueble, el mismo criterio se ha aplicado en la elección del mobiliario, utensilios y artefactos.',
    location: { street: 'Ruta que conecta La Bolsa con Alta Gracia', city: 'Los Aromos', state: 'Córdoba', zipcode: '' },
    beds: 3, baths: 2, square_feet: 235,
    amenities: ['Piscina', 'Quincho', 'Jardín', 'Cochera', 'Amoblado'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2022/10/LOS-AROMOS-EP-25.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2022/10/LOS-AROMOS-EP-23.jpg'],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: 235, garage: 1,
    services: ['Luz (EPEC)', 'Agua (pozo 50 mts.)'],
    titles_status: null,
    interior: {},
    exterior: {},
    price: null,
  },
  {
    name: 'Córdoba, Alta Gracia, Fracción de 1,4 Hectáreas sobre ruta c45',
    type: 'Campo',
    description: 'SE VENDE Fracción sobre ruta c-45 colindante con el barrio RESERVA TAJAMAR. Con aprox. 107 mts. de frente sobre ruta c-45 y 90 mts. sobre calle paralela a la de Reserva Tajamar en el fondo. Ubicada dentro del Eje Comercial de Servicios R.P.C45 del POU de Alta Gracia. El inmueble se encuentra dentro del ejido de la ciudad de Alta Gracia y a 2,5 km de pleno centro. Posee un ingreso directo sobre la ruta c45 y esta a 1,2 km de la rotonda de enlace con Ruta 5, lo que facilita la logística desde y hacia el inmueble. Cuenta con servicio de Luz y una perforación de agua de 30 mts. de profundidad.',
    location: { street: 'Ruta C45', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 14000,
    amenities: [],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2022/01/1.4-HAS-EJE-COMERCIAL-C45-3-scaled.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2022/01/1.4-HAS-EJE-COMERCIAL-C45-2-scaled.jpg'],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz', 'Agua (perforación 30m)'],
    titles_status: null,
    interior: {},
    exterior: {},
    price: 'USD 460,000',
  },
  {
    name: 'Córdoba, Los Molinos, 22 Hectáreas sobre Ruta 5 frente al lago Los Molinos',
    type: 'Gran Inversión',
    description: '22 has sobre ruta provincial 5. 380 mts de frente sobre ruta 5. Perímetro alambrado parcialmente con varillas de acero y 4 hilos. Servicio de luz a 200 mts. 2 vertientes de agua propias. Camino hacia la cima de la fracción a reacondicionar. Títulos perfectos.',
    location: { street: 'Ruta Provincial 5', city: 'Los Molinos', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 220000,
    amenities: ['Lago', 'Costa de río', 'Vertientes'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2020/10/22HMOLINOS-3.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2020/10/22HMOLINOS-2.jpg'],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Electricidad', 'Agua'],
    titles_status: 'Títulos perfectos',
    interior: {},
    exterior: {},
    price: 'USD 330,000',
  },
  {
    name: 'Córdoba, Anisacate, 3.300 m2 con frente sobre Ruta 5 y 150 mts de costa s/Rio Anisacate',
    type: 'Campo',
    description: 'El inmueble cuenta con: Predio de 3.300 m2 de tierra con 150 mts de costa y bajada propia al Río Anisacate. 2.596 m2 con títulos perfectos. 700 m2 con derechos y acciones. Salón comercial de 100 m2 con parrilla y 2 baños públicos. 3 departamentos de 1 dormitorio con baño. 2 baños públicos en predio. Importante renta por temporada. Flujo de 150 vehículos diarios en predio. Luz, Agua de red y Gas Natural sobre el frente.',
    location: { street: 'Ruta 5', city: 'Anisacate', state: 'Córdoba', zipcode: '' },
    beds: 3, baths: 7, square_feet: 200,
    amenities: ['Río', 'Salón comercial', 'Departamentos'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2020/09/20200904_115310-scaled.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2020/09/20200904_115007-scaled.jpg'],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: 200, garage: null,
    services: ['Luz', 'Agua de Red', 'Gas Natural'],
    titles_status: '2.596 m2 con títulos perfectos; 700 m2 con derechos y acciones',
    interior: {},
    exterior: {},
    price: null,
  },
  {
    name: 'Alta Gracia, Córdoba, Barrio Norte, Departamento de 2 dormitorios, inmejorable ubicación EN VENTA',
    type: 'Departamento',
    description: 'Inmejorable ubicación, en Calle Olmos y a 100 metros de Av. Belgrano, con vista a las sierras, a 200 metros de parada de supermercados, farmacias y todo tipo de comercios. El edificio cuenta con un amplio hall de ingreso, 2 ascensores y jardín parquizado con bancos para disfrutar. La unidad cuenta con 2 dormitorios con placares completos, baño con ducha, cocina con lavadero, comedor diario/office, living/comedor con amplio balcón. Calefactores y ventiladores en todos los ambientes. Aberturas de aluminio. En total posee 68 metros cuadrados. Edificio en excelente estado de mantenimiento. Apto Crédito.',
    location: { street: 'Calle Olmos y Av. Belgrano, Barrio Norte', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 2, baths: 1, square_feet: 68,
    amenities: ['Ascensor', 'Jardín', 'Balcón', 'Apto Crédito'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2024/05/DPTO8BOLMOS-5.jpeg', 'https://roggeroyroma.com.ar/wp-content/uploads/2024/05/DPTO8BOLMOS-2.jpeg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 68, garage: null,
    services: ['Agua', 'Luz', 'Gas', 'Cloacas'],
    titles_status: 'Títulos Perfectos',
    interior: { aberturas: 'Aluminio', pisos: null, calefaccion: 'Calefactores y ventiladores en todos los ambientes' },
    exterior: {},
    price: 'USD 110,000',
  },
  {
    name: 'Córdoba, San Clemente, Fracciones de 1 Hectárea',
    type: 'Campo',
    description: 'Títulos Perfectos. Exclusiva costa de río. Privacidad y exclusividad. El Loteo se compone de 15 Fracciones, de no menos 1 hectárea cada una, estudiadas y diseñadas para generar un Club de Campo que mantiene y respeta la naturaleza. El Club House se encuentra en medio de un remanso tranquilo de árboles autóctonos y pinos. Desde el parque se accede al río con bajada propia y 4 mts de costa sobre uno de los límites del campo. A otros 15 mts por un bonito camino en el bosque se baja al arroyo con un precioso salto de agua e inmediatamente una hectárea con diversos árboles frutales como Peras, Cerezas, Limones y Duraznos. El predio posee casi 18 hectáreas con una vertiente y 400 mts de costa de río; posee vistas a la Quebrada del Condorito, y esta rodeado de verde propio con árboles autóctonos como Molles, Talas, Cocos, Espinillos y Pinos de diferentes especies.',
    location: { street: '', city: 'San Clemente', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 10000,
    amenities: ['Río', 'Costa de río', 'Club House', 'Vertiente'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2018/08/18hasSanClem-0.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2018/10/18hasSanClem-1.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Agua de Pozo', 'Luz Solar', 'Gas Envasado'],
    titles_status: 'Títulos Perfectos',
    interior: { aberturas: 'Madera de Cedro', pisos: 'Madera de Eucaliptus', calefaccion: '2 Salamandras, 1 Estufa Rusa, Hogar en Living y calefactor a gas en baño' },
    exterior: { techos: 'Losa / Chapa galvanizada con interior en madera' },
    price: null,
  },
  {
    name: 'Córdoba, Los Gigantes, Campo de 1250 Hectáreas',
    type: 'Gran Inversión',
    description: 'Campo de 1.250 has. ubicado en la zona de Los Gigantes, Provincia de Córdoba. El campo es de extraordinaria belleza y con distintas variantes de paisaje, tiene extensas pampas con buen pasto, y otras de piedras como intercaladas en una alfombra verde en la epoca de lluvias. Parte de la imponente Sierra de los Gigantes se encuentra dentro del campo. Los ríos El Cajón y El Malambo nacen en el campo. Posee cascadas hermosas y piletones naturales de agua. Numerosas vertientes. Casco de campo en piedra semi destruido con corrales de piedra. Alamedas de sauces. Varias cortinas. Rainfall: aproximadamente 1.200 mm anuales. Fauna: lagartijas verdes, ranas coloridas, águilas, zorzales, buitres, caranchos, condores, liebres, zorros, pumas. 80% alambrado. Ganadería. Potencial para Generación de Energía Eólica.',
    location: { street: '', city: 'Los Gigantes', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 12500000,
    amenities: ['Río', 'Cascadas', 'Vertientes', 'Casco de campo'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: [],
    is_featured: true,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: [],
    titles_status: '950 has títulos perfectos, resto derechos y acciones',
    interior: {},
    exterior: {},
    price: null,
  },
  {
    name: 'La Paisanita, Campo de 30 Has. sobre Río con Casco, Galpón, casa de Puestero y 3 Cabañas',
    type: 'Gran Inversión',
    description: 'Exclusiva propiedad de 30 hectáreas en La Paisanita sobre el río con casco principal de 350 m², galpón de 300 m², casa de puestero y 3 cabañas. 160 metros de costa sobre el río con pileta natural de 4 mts de profundidad promedio. El casco principal incluye 70 m² sótano, 70 m² galería, 15 m² mirador, cocina con horno Ariston, living-comedor de 90 m² con hogar de piedra, terraza de 300 m². Cabaña de Piedra de 70 m² a 20 mts del agua. Cabaña Blanca y Cabaña Azul de 60 m² cada una. Galpón de 15×20 mts con paredes de ladrillo. 30,000 litros cisterna. Piscina de 4×8 mts. Seguridad con cámaras y acceso remoto.',
    location: { street: '', city: 'La Paisanita', state: 'Córdoba', zipcode: '' },
    beds: 1, baths: 2, square_feet: 350,
    amenities: ['Río', 'Piscina', 'Galpón', 'Cabañas', 'Casa de Puestero', 'Seguridad'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2020/08/LA-TAIMADA-41-scaled.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2020/08/LA-TAIMADA-27-scaled.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 350, garage: null,
    services: ['Agua', 'Energía Eléctrica Trifásica (EPEC)'],
    titles_status: 'En Venta',
    interior: { aberturas: 'Ventanas alemanas con doble vidriado y movimiento oscilo-batiente, mosquiteros incorporados', pisos: null, calefaccion: 'Sistema de calefacción central a gas con radiadores' },
    exterior: { techos: 'Tejas coloniales' },
    price: null,
  },
  {
    name: 'Soñada Casona sobre 10 Has con 60 mts de costa propia sobre Río',
    type: 'Gran Inversión',
    description: 'Hermosa Casona de época con vista al Valle y 60 mts. de costa sobre río. Construida en la Montaña sobre un prédio de 10 has. y con rápido acceso al centro de la ciudad. Casa principal con ingreso por portón y porche, 3 dormitorios, 2 baños, cocina, living-comedor. Casa de puestero con 2 dormitorios, 1 baño, living-comedor, cocina, lavadero. Baño con shower, cuarto de limpieza, cuarto de guarda de alimentos, escritorio. Área de BBQ con 2 braseros y horno. Epén para animales con cuarto contiguo. Establo (conversible a departamento con pileta). Molino funcional. 60 metros de costa sobre río.',
    location: { street: '', city: 'Huerta Grande', state: 'Córdoba', zipcode: '' },
    beds: 5, baths: 3, square_feet: null,
    amenities: ['Río', 'Casa de Puestero', 'BBQ', 'Establo', 'Molino'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: [],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: 2,
    services: ['Luz', 'Agua de Pozo'],
    titles_status: 'En Venta Amoblada',
    interior: {},
    exterior: {},
    price: 'USD 350,000',
  },
  {
    name: 'Casa de 3 dormitorios en El Anglo, Alta Gracia, Córdoba',
    type: 'Casa',
    description: 'Casa de 3 dormitorios con 2 baños, piscina de 8 x 4 metros, en el barrio El Anglo de Alta Gracia, Córdoba. Sobre terreno de 1,276 m² con 300 m² cubiertos.',
    location: { street: 'El Anglo', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 3, baths: 2, square_feet: 300,
    amenities: ['Piscina', 'Parrilla', 'Jardín'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2026/03/ELANGLO-YOL-4.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2026/03/ELANGLO-YOL-7.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 300, garage: 1,
    services: ['Electricidad', 'Gas', 'Agua', 'Cloacas'],
    titles_status: 'En Venta',
    interior: { aberturas: null, pisos: null, calefaccion: 'Calefacción central' },
    exterior: {},
    price: 'USD 350,000',
  },
  {
    name: 'Córdoba, Anisacate, Villa Montenegro, Casa de 3 hab. a 1 cuadra de la Ruta',
    type: 'Casa',
    description: 'Casa de 3 habitaciones a 1 cuadra de la Ruta en Villa Montenegro, Anisacate. Posee piscina y títulos perfectos.',
    location: { street: 'Villa Montenegro', city: 'Anisacate', state: 'Córdoba', zipcode: '' },
    beds: 3, baths: 1, square_feet: 210,
    amenities: ['Piscina'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2026/03/VILLAMONTEALLENDE-3.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2026/03/VILLAMONTEALLENDE-5.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 210, garage: 1,
    services: ['Electricidad', 'Agua de red (pozo propio en la calle)', 'Gas Envasado'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 150,000',
  },
  {
    name: 'La Paisanita, Córdoba, Casa de 3 dormitorios sobre el Rio en Loteo cerrado',
    type: 'Casa',
    description: 'Excelente propiedad con acceso privado al río con playas de arena y pileta natural. Ubicada en loteo cerrado con expensas mínimas, en valle protegido de vientos. Construcción de calidad sin detalles. Cocina-comedor-living integrada que abre a terraza cubierta con grill que mira hacia jardín y vistas al río, más fogón.',
    location: { street: '', city: 'La Paisanita', state: 'Córdoba', zipcode: '' },
    beds: 3, baths: 3, square_feet: 200,
    amenities: ['Río', 'Pileta natural', 'Seguridad', 'Fogón', 'Terraza'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/08/BALDACCINIPAISA-25.jpeg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/08/BALDACCINIPAISA-26.jpeg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 200, garage: 2,
    services: ['Energía Eléctrica'],
    titles_status: 'En Venta',
    interior: { aberturas: null, pisos: null, calefaccion: 'Aire acondicionado / calefacción + hogar' },
    exterior: {},
    price: 'USD 220,000',
  },
  {
    name: 'Casa de 2 dormitorios en Alta Gracia Country Golf',
    type: 'Casa',
    description: 'Propiedad situated dentro del complejo residencial Alta Gracia Country Golf. Ofrece espacios de living moderados con sustanciales áreas semi-cubiertas adecuadas para el disfrute al aire libre. Superficie total de 1,004 m².',
    location: { street: 'Alta Gracia Country Golf', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 2, baths: 2, square_feet: 175,
    amenities: ['Seguridad 24hs', 'Golf', 'Área semi-cubierta'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: [],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 175, garage: 4,
    services: ['Electricidad', 'Agua', 'Gas (próximo)'],
    titles_status: 'En Venta',
    interior: {},
    exterior: {},
    price: 'USD 310,000',
  },
  {
    name: 'Casa de 5 dormitorios en B° Pellegrini, Alta Gracia Córdoba',
    type: 'Casa',
    description: 'Se venta propiedad de grandes dimensiones en uno de los mejores barrios de la ciudad de Alta Gracia, a metros del parque del Sierras Hotel. Excelente y tranquilo entorno. Todos los servicios. Distribuida en 2 plantas: living, office, cocina comedor, lavadero, 2do living más privado. Requiere mínima inversión para modernización.',
    location: { street: 'B° Pellegrini', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 5, baths: 2, square_feet: 306,
    amenities: ['Patio', 'Cochera', 'Parrilla'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/04/ROQUECELEN-22.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/04/ROQUECELEN-21.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 306, garage: 3,
    services: ['Gas natural', 'Agua de red', 'Energía eléctrica', 'Cloacas'],
    titles_status: 'En Venta',
    interior: { aberturas: 'Aberturas y postigos de aluminio', pisos: null, calefaccion: null },
    exterior: {},
    price: 'USD 250,000',
  },
  {
    name: 'Alta Gracia, Córdoba, Casa de 3 dormitorios en B° El Golf',
    type: 'Casa',
    description: 'Hermosa propiedad de 3 dormitorios y 3 baños, moderna y funcional. Con varios niveles se aprovecha el terreno brinda cómodo y múltiples espacios para disfrutar. Grandes balcones a los cuales se accede desde los dormitorios a través de puerta ventanas. El dormitorio principal se encuentra jerarquizado, con baño en suite y tiene acceso directo a la piscina. Todos los ambientes poseen excelente luz natural.',
    location: { street: '', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 3, baths: 3, square_feet: 233,
    amenities: ['Piscina', 'Balcones', 'Parrilla'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/03/CASABGOLFPOWELL-3.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/03/CASABGOLFPOWELL-9.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 233, garage: null,
    services: ['Luz', 'Agua de Red', 'Gas Natural', 'Cloacas'],
    titles_status: null,
    interior: { aberturas: null, pisos: null, calefaccion: 'central' },
    exterior: {},
    price: 'USD 295,000',
  },
  {
    name: 'Casa de 5 dormitorios en Potrerillo de Larreta, Alta Gracia, Córdoba',
    type: 'Casa',
    description: 'Hermosa propiedad de 600 m2 cubiertos en Potrerillo de Larreta Resort & Country club, cuenta con 5 dormitorios, 5 baños, cocina comedor y living organizados en ambientes amplios y luminosos con excelentes vistas, de buena construcción, con detalles a mejorar. EXCELENTE PRECIO. OPORTUNIDAD.',
    location: { street: 'Potrerillo de Larreta Resort & Country Club', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 5, baths: 5, square_feet: 600,
    amenities: ['Piscina', 'Parrilla', 'Seguridad', 'Aire acondicionado central'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/02/RAZZUKPOTRE-1.jpeg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/02/RAZZUKPOTRE-2.jpeg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 600, garage: null,
    services: ['Piscina 4 x 9 metros', 'Calefacción central', 'Aire acondicionado central', 'DVH (aberturas)'],
    titles_status: 'En Venta',
    interior: { aberturas: 'DVH', pisos: null, calefaccion: 'central' },
    exterior: {},
    price: 'USD 380,000',
  },
  {
    name: 'Córdoba, Potrero de Garay, Náutico Los Molinos, Dpto. en Monte Molinos',
    type: 'Departamento',
    description: 'Se venden exclusivos departamentos en un entorno único de rápido y fácil acceso.',
    location: { street: '', city: 'Potrero de Garay', state: 'Córdoba', zipcode: '' },
    beds: 2, baths: 1, square_feet: 69,
    amenities: ['Piscina', 'Solarium', 'Cocheras cubiertas', 'Seguridad'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2021/03/MONTEMOLINOS-11.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2021/03/MONTEMOLINOS-10.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 69, garage: null,
    services: ['Luz', 'Agua de pozo'],
    titles_status: 'En Venta',
    interior: {},
    exterior: {},
    price: null,
  },
  {
    name: 'Hermoso Dúplex de 2 dormitorios a 3 cuadras del centro, Alta Gracia, Córdoba',
    type: 'Departamento',
    description: 'Living-Comedor integrado a Patio y Jardín con Parrilla. Toilette bajo escalera con mesada de Travertino. Cocina-Lavadero: mesadas de granito gris Mara para Muebles de cocina bajo y sobre mesada. Primer piso: Espacio Biblioteca, Escritorio, Placard pasillo. Antebaño con bacha, mesada de Travertino. Baño completo con Bañera. Dormitorios con Placards de piso a techo.',
    location: { street: 'Cjal. Alonso esq. Lozada', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 2, baths: 2, square_feet: 140,
    amenities: ['Patio', 'Jardín', 'Parrilla', 'Cochera', 'Baulera'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2020/09/COSTENAR-1-1.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2020/09/COSTENAR-2-1.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 140, garage: 1,
    services: ['Gas Natural', 'Cloacas', 'Agua', 'Luz'],
    titles_status: 'En Venta',
    interior: { aberturas: 'MDF con canto de aluminio', pisos: null, calefaccion: 'Calefón y Cocina máxima calidad' },
    exterior: {},
    price: null,
  },
  {
    name: 'Alta Gracia, Córdoba, Departamento de 3 Dormitorios en zona de El Golf',
    type: 'Departamento',
    description: 'Hermoso departamento en complejo cerrado de Barrio El Golf. Cocina equipada de excelente calidad. Dormitorios con piso de madera, el principal con vestidor, baño y ante baño en suite de gran tamaño. 2 baños con ante baño. Living comedor con salida a balcon y hermosa vista. Lavadero. Calefaccion por loza radiante y aire acondicionado central. Doble cochera de gran tamaño. Terraza propia de gran tamaño con asador. Complejo con piscina, zoom con asador, seguridad.',
    location: { street: '', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 3, baths: 2, square_feet: 234,
    amenities: ['Piscina', 'SUM', 'Asador', 'Terraza', 'Seguridad', 'Cochera'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2019/10/PALMETTOPIÑ-12-1.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2019/10/PALMETTOPIÑ-1.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 234, garage: 2,
    services: ['Luz', 'Agua de Red', 'Gas Natural', 'Cloacas'],
    titles_status: 'En Venta',
    interior: { aberturas: 'Aluminio DVH', pisos: 'madera y porcelanato', calefaccion: 'loza radiante' },
    exterior: { techos: 'loza' },
    price: null,
  },
  {
    name: 'Córdoba, Despeñaderos, 8 Hectáreas a 400mts de acceso ruta 36',
    type: 'Campo',
    description: 'Campo de 8 hectáreas con frentes sobre Av. Jose de la Quintana (340 mts aprox) y camino a ruta 36 (330 mts aprox). Frente a NUTRIFARMS y YPF AGRO. La zona cuenta con Luz, agua y gas.',
    location: { street: 'Av. Jose de la Quintana y camino a ruta 36', city: 'Despeñaderos', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 80869,
    amenities: [],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/07/8HASDESP-17.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/07/8HASDESP-20.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz', 'Agua', 'Gas'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 400,000',
  },
  {
    name: 'Córdoba, Alta Gracia, Salón comercial de 956m2 sobre Ruta C-45 en Eje Comercial y de Servicios',
    type: 'Inmueble Comercial',
    description: 'El inmueble posee: 2 camarines privados, Cocina equipada con hornos, cocinas, freidoras, mesas de trabajo y cámaras frigoríficas, Vajilla completa para 300 personas, 50 mesas plegables, Fondo de comercio en funcionamiento.',
    location: { street: 'Ruta C-45', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 956,
    amenities: ['Camarines privados', 'Cocina equipada', 'Estacionamiento'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/05/SOnADA-1.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/05/SOnADA-3.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 956, garage: null,
    services: ['Luz', 'Agua de pozo'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 890,000',
  },
  {
    name: 'Córdoba, Alta Gracia, 2 Hectáreas sobre autovía Ruta 5, zona Industrial',
    type: 'Terreno',
    description: 'Excelente ubicación sobre Autovía Ruta 5, frente a rotonda que conecta al camino que conduce a Falda del Carmen, Villa Carlos Paz y Altas Cumbres. A 800 metros del Complejo de Oreste Berta, Verdol y 400 metros de Dolomita. Luz, agua a 20 mts. de profundidad. 71 mts de frente sobre ruta. Estudio de Suelos realizado.',
    location: { street: 'Autovía Ruta 5', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 20000,
    amenities: ['Zona Industrial', 'Cercado perimetral'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2020/09/2HAS-RUTA5-1.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2020/09/2HAS-RUTA5-2.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz', 'Agua'],
    titles_status: null,
    interior: {},
    exterior: { techos: null },
    price: null,
  },
  {
    name: 'Córdoba, Santa Ana, 5.6 Hectáreas sobre autovía Ruta 5',
    type: 'Terreno',
    description: 'Se venden 5,6 hectáreas sobre Autovía Ruta-5: Excelente acceso (a 10\' de Alta Gracia y 20\' de Córdoba), Frente comercial de 200 mts sobre ruta, Posibilidad de fraccionamiento de tierra para loteo, Fracción totalmente llana y aprovechable, El inmueble posee oficinas comerciales (edificio en 2 plantas) y 2 casas (1 en estado precario). Se reciben inmuebles en pago al 100% del valor de venta.',
    location: { street: 'Autovía Ruta 5', city: 'Santa Ana', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 56291,
    amenities: ['Oficinas comerciales', 'Casas'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/05/56-HAS-HM-4.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/05/56-HAS-HM-7.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz trifásica', 'Agua de pozo'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 1,967,018',
  },
  {
    name: 'Alta Gracia, Córdoba, Casa antigua con 5 dormitorios en B° Norte',
    type: 'Casa',
    description: 'Se venta Casa Antigua a 2 cuadras de pleno centro de la ciudad de Alta Gracia. Alta Gracia es una zona estratégica para desarrollar actividades comerciales relacionadas con el turismo dentro la provincia de Córdoba, ya que se encuentra a 30 minutos de Córdoba Capital por autopista, a 20 minutos de Carlos Paz, a 35 minutos de lago Los Molinos y a 40 minutos de Villa General Belgrano. El inmueble esta ubicado dentro de la ZONA CENTRAL Institucional-Administrativa-Comercial de Alta Gracia, según el Plan de Ordenamiento Urbano y Territorial del Municipio; lo que le otorga gran variedad de usos comerciales (Alojamiento Transitorio, Restaurante, Bar, entre otros.). La propiedad cuenta con 2 accesos, uno por calle Olmos (vehicular y peatonal) y otro por calle Brasil (peatonal). También cuenta con dormitorios en planta alta y planta baja. Permite un uso habitacional y comercial simultaneo. Es decir, se puede vivir en una parte del mismo y desarrollar una actividad comercial en la otra parte, ambos usos independientemente uno del otro.',
    location: { street: 'Calle Olmos y Calle Brasil', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 5, baths: 5, square_feet: 298,
    amenities: ['Internet', 'Telefono', '2 Accesos'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2023/04/OLMOSBRASIL-48-1.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2023/04/OLMOSBRASIL-51.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 298, garage: 2,
    services: ['Luz', 'Agua de Red', 'Gas Natural', 'Cloacas', 'Internet', 'Telefono'],
    titles_status: 'Títulos Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 220,000',
  },
  {
    name: 'Alta Gracia, Córdoba, Casa Antigua de 5 habitaciones a metros del Tajamar',
    type: 'Casa',
    description: 'Se venta hermosa Casona en pleno centro de la ciudad de Alta Gracia. En una zona estratégica de la provincia de Córdoba para el turismo, ya que se encuentra a 30 minutos de Córdoba Capital por autopista, a 20 minutos de Carlos Paz, a 35 minutos de lago Los Molinos y a 40 minutos de Villa General Belgrano. El inmueble se encuentra ubicado a 100 metros del Tajamar y la Estancia Jesuítica de Alta Gracia. Esta dentro de la ZONA CENTRAL Institucional-Administrativa-Comercial de Alta Gracia, según el Plan de Ordenamiento Urbano y Territorial del Municipio; lo que le otorga gran variedad de usos comerciales (Alojamiento Transitorio, Restaurante, Bar, entre otros.). Muy buen estado de conservación. Todos los servicios conectados.',
    location: { street: '', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: 5, baths: null, square_feet: 279,
    amenities: ['Internet', 'Telefono'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2023/04/PARAVACHASCA-39.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2023/04/PARAVACHASCA-40.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: 279, garage: null,
    services: ['Luz', 'Agua de Red', 'Gas Natural', 'Cloacas', 'Internet', 'Teléfono'],
    titles_status: 'Títulos Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 220,000',
  },
  {
    name: 'Alta Gracia, Córdoba, Lote de 877 m2 con vista a las sierras en B° El Golf',
    type: 'Terreno',
    description: 'Inmejorable ubicación y entorno. Visuales excepcionales. Último lote disponible en esta zona con vistas a las sierras.',
    location: { street: '', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 877,
    amenities: ['Vistas a las sierras'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2026/02/877m2GARCIAL-3.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2026/02/877m2GARCIAL-2.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz', 'Agua', 'Gas'],
    titles_status: 'Derechos y Acciones de más de 50 años',
    interior: {},
    exterior: {},
    price: 'USD 85,000',
  },
  {
    name: 'Alta Gracia, Córdoba, Lote de 1.037 m2 en Barrio Residencial El Golf',
    type: 'Terreno',
    description: 'Lote en venta en Barrio Residencial El Golf, Alta Gracia, Córdoba. Superficie de 1.037 m2 con servicios de luz, agua y gas. Títulos perfectos.',
    location: { street: '', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 1037,
    amenities: [],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/12/1037m2ELGOLF-11.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/12/1037m2ELGOLF-6.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz', 'Agua', 'Gas'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 135,000',
  },
  {
    name: 'Se vende hermoso lote de 1070 m2 con excelente entorno en Alta Gracia, Serralta',
    type: 'Terreno',
    description: 'El Barrio está ubicado al ingreso de la ciudad de Alta Gracia, sobre autovía ruta 5 y ofrece excelente acceso y rápida salida hacia Córdoba, Carlos Paz. El lote se encuentra en la zona más linda dentro del Barrio, cuenta con doble acceso por sus 2 frentes, excelente entorno y bellas vistas a las sierras. Ya consolidado, el Barrio Serralta, ofrece un nivel de vida superior a un valor realmente accesible. Cuenta con servicios de Agua corriente y energía eléctrica subterráneos.',
    location: { street: 'Barrio Serralta, sobre autovía ruta 5', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 1072,
    amenities: ['Vistas a las sierras', 'Doble acceso'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2025/04/SERRALTAFR-15.jpeg', 'https://roggeroyroma.com.ar/wp-content/uploads/2025/04/SERRALTAFR-14.jpeg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Agua corriente', 'Energía eléctrica subterránea'],
    titles_status: null,
    interior: {},
    exterior: {},
    price: 'USD 35,000',
  },
  {
    name: 'Córdoba, Potrero de Garay, 2 lotes (901m2 y 1.066m2) sobre ruta y a 250 metros del Lago Los Molinos',
    type: 'Terreno',
    description: '2 lotes (901m2 y 1.066m2) sobre ruta y a 250 metros del Lago Los Molinos',
    location: { street: '', city: 'Potrero de Garay', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 901,
    amenities: ['Lago'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2024/05/LOTESPOTRERO-8.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2024/05/LOTESPOTRERO-12.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz', 'Agua'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 50/m2',
  },
  {
    name: 'Alta Gracia, Córdoba, Lote de 1.037 m2 en El Anglo Barrio Privado',
    type: 'Terreno',
    description: 'Sobre Calle Monseñor Jesús Roldan, enclavado en la mejor zona de Alta Gracia (Barrio Residencial El Golf), El Anglo se ha consolidado como uno de los barrios privados mas bellos y completos de Alta Gracia. Cuenta con bellísimas visitas a las sierras al Oeste y la llanura al Este. También goza de excelentes visuales y vecinos por estar abrazado en su perímetro Norte y Este por el Alta Gracia Country Golf. Cuenta con rápido acceso a las rutas 5 y C-45. Todos los servicios son subterráneos y llegan a la puerta de sus lotes. Seguridad las 24hs con control de ingreso y circulación interna por todo el barrio. Se encuentra vendido en mas de un 80% y las propiedades edificadas en el mismo son de primer nivel. Sin dudas es uno de los mejores lugares para vivir en Alta Gracia.',
    location: { street: 'Calle Monseñor Jesús Roldan', city: 'Alta Gracia', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 1037,
    amenities: ['Barrio Privado', 'Seguridad 24hs', 'Vistas a las sierras'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2024/05/ELANGLOMASSAFRA-8.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2024/05/ELANGLOMASSAFRA-7.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz', 'Agua', 'Gas', 'Cloacas'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 65,000',
  },
  {
    name: 'Córdoba, La Serranita, Lote de 4.745m2 a 85 mts. del Asfalto',
    type: 'Terreno',
    description: 'La fracción cuenta con rápido acceso desde la ruta provincial N°5 a solo 400 metros. Acceso inmediato a la red de Gas Natural a escasos metros. Agradables y aprovechables pendientes. Entorno tranquilo con buena vista a las sierras al Oeste. Títulos perfectos. Posibilidad de vender menor superficie con gastos de subdivisión a cargo del comprador.',
    location: { street: '85 metros del asfalto, 400 metros de Ruta Provincial N°5', city: 'La Serranita', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 4745,
    amenities: ['Vistas a las sierras'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2024/02/Serranita-8.jpg', 'https://roggeroyroma.com.ar/wp-content/uploads/2024/02/Serranita-30.jpg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz de Cooperativa', 'Gas natural (a escasos metros)', 'Agua de Red'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 120,000',
  },
  {
    name: 'Córdoba, Falda del Carmen, 1,5 Hectáreas a 500 mts. del Asfalto',
    type: 'Campo',
    description: 'La fracción cuenta con rápido acceso desde la ruta provincial E96 a solo 500 mts. (camino al observatorio). Totalmente llana y aprovechable. Entorno tranquilo con buena vista a las sierras al Suroeste. Títulos perfectos. Mensurada y amojonada. Posibilidad de recibir inmueble por menor valor en Córdoba Capital.',
    location: { street: 'Ruta Provincial E96', city: 'Falda del Carmen', state: 'Córdoba', zipcode: '' },
    beds: null, baths: null, square_feet: 15318,
    amenities: ['Vistas a las sierras'],
    rates: { nightly: null, weekly: null, monthly: null, sale: true, price: null },
    seller_info: { name: 'Roggero & Roma', email: 'info@roggeroyroma.com.ar', phone: '(03547) 425454' },
    images: ['https://roggeroyroma.com.ar/wp-content/uploads/2024/02/FALDADELC-14.jpeg', 'https://roggeroyroma.com.ar/wp-content/uploads/2024/02/FALDADELC-1.jpeg'],
    is_featured: false,
    operation: "venta", status: "active",
    covered_area: null, garage: null,
    services: ['Luz (a 350 mts)', 'Agua de perforación (30 mts de profundidad)'],
    titles_status: 'Perfectos',
    interior: {},
    exterior: {},
    price: 'USD 78,000',
  },
];

async function seedProperties() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGO_URI);
    console.log('Connected!\n');

    await Property.deleteMany({});
    console.log('Cleared existing properties\n');

    const inserted = await Property.insertMany(properties);
    console.log(`Inserted ${inserted.length} properties successfully!`);

    await mongoose.connection.close();
    console.log('Done!');
    process.exit(0);
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

seedProperties();
